language: objective-c
osx_image: xcode10.2
env:
    - TEST_PLATFORM='platform=iOS Simulator,OS=12.2,name=iPhone XÊ€'
rvm:
    - 2.3.7
before_install:
    - gem install slather
    - gem install xcpretty -N --no-document
install:
    - ./.travis/install.sh
script: ./.travis/test.sh
after_success: slather
